name: cron
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  stress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: make stress
